### ISSUE TITLE
Can't run app with express-train

### ISSUE THREAD

**Issue by mrodrig** [autoric/express-train#48]
Hi,

I'm not sure why, but when I try to run my app using `express@4.13.x` and `express-train@4.0.x`, I'm getting the following error when trying to run my app.  I tried using the generator (generator-express-train) and kept getting similar errors with the setup that was generated too.

Error:

```
$ node app/index.js 

[2016-02-29 19:31:58.846] [LOG]   Configuring Express-Train from file: ../config

/home/mrodrig/lvm/node_modules/express-train/lib/app.js:136
      throw new Error(file.path+': '+err)
      ^

Error: /home/mrodrig/lvm/node_modules/abbrev/CONTRIBUTING.md: SyntaxError: Unexpected identifier
    at /home/mrodrig/lvm/node_modules/express-train/lib/app.js:136:13
    at forOwn (/home/mrodrig/lvm/node_modules/lodash/dist/lodash.js:1907:15)
    at Function.forEach (/home/mrodrig/lvm/node_modules/lodash/dist/lodash.js:3044:9)
    at ExpressTrain (/home/mrodrig/lvm/node_modules/express-train/lib/app.js:131:5)
    at Object.<anonymous> (/home/mrodrig/lvm/app/index.js:27:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```

Here's my express-train config in index.js:

``` javascript
var tree = train(__dirname,
    {
        config: {path: environment.etFileLocation}
    });
```

Is there something wrong here? Why is it looking in the node_modules directory?

Thanks in advance!

**Comment by mrodrig** [comment]
Sorry, think I figured it out.
